### PR TITLE
fix: apply styles based on reactive attributes

### LINKED ISSUE #194: [Bug]: reactive $class changes are not being applied
### Issue Category

Behavioral Bug

### Bug Description

Only one line become red if the `class` is used vs `$class`.  If `$class` is used then both lines are not red

```jsx
component ArrayTest() {
	let $a = 'red';
	let $b = '';

	<div class={$a} onClick={() => $a ==='red' ? $a = '' : $a = 'red'}>{'works'}</div>
	<div $class={$b} onClick={() => $b ==='red' ? $b = '' : $b = 'red'}>
		{'click to make red: '}
		{$b || 'empty class'}
	</div>

	<style>
		.red { background: red }
	</style>
}
```

and here both don't work as they both use `$class`

```jsx
component ArrayTest() {
	let $a = 'red';
	let $b = '';

	<div $class={$a} onClick={() => $a ==='red' ? $a = '' : $a = 'red'}>{'works'}</div>
	<div $class={$b} onClick={() => $b ==='red' ? $b = '' : $b = 'red'}>
		{'click to make red: '}
		{$b || 'empty class'}
	</div>

	<style>
		.red { background: red }
	</style>
}
```

reported in comment on #5 

### Reproduction Steps

Click on each line to toggle red class.

### Environment

```markdown
- latest and likely earlier
```

### Additional Context

_No response_

### Checklist

- [x] I've searched for existing issues
- [ ] I'm willing to help implement a fix

### PR DESCRIPTION
**Pull request by moka-ayumu**
Fixes #194 

This PR fixes a bug where the compiler did not correctly handle attributes starting with a dollar sign, such as `$class`.
`attribute_matches` function has been updated to correctly recognize attributes prefixed with a dollar sign.

### CODE REVIEW

**Comment by leonidaz** [comment]
Could you add a test please?

**Comment by moka-ayumu** [comment]
> Could you add a test please?

@leonidaz 
I've updated the test code to check for classes starting with `ripple-` because the style tag isn't applied in the test environment, which prevented using `getComputedStyle` to check for applied styles.

File: packages/ripple/src/compiler/phases/2-analyze/prune.js [hunk 1]
```diff
@@ -405,12 +405,15 @@ function attribute_matches(node, name, expected_value, operator, case_insensitiv
...
+
+		const lowerCaseName = name.toLowerCase();
+		if (![lowerCaseName, `$${lowerCaseName}`].includes(attribute.name.name.toLowerCase())) continue;
 
 		if (expected_value === null) return true;
 
 		if (is_text_attribute(attribute)) {
-			return test_attribute(operator, expected_value, case_insensitive, attribute.value.value);
+			if (test_attribute(operator, expected_value, case_insensitive, attribute.value.value))
+				return true;
```
Comment (leonidaz) [inline packages/ripple/src/compiler/phases/2-analyze/prune.js]: this should be reverted

**Review by leonidaz — CHANGES_REQUESTED** [review]
ok, just a small change and then we can merge.

**Review by leonidaz — APPROVED** [review]

**Comment by leonidaz** [comment]
thank you!  

Note: in the future after a review, please add another commit vs just pushing in the same ones as it no longer possible to verify the requested changes.

We typically (100% at this point) squash commits anyway.
